name: Build C3 (MSVC)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build C3 (MSVC)
    strategy:
      matrix:
        platfom: [x86, x64]
        configuration: [Debug, ReleaseWithDebInfo, Release]
    runs-on: windows-2022
    
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[16.10]'
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Dotnet restore
      run: msbuild Src/C3.sln "/t:restore"

    - name: Build MSVC
      run: msbuild Src/C3.sln "/p:Platform=${{ matrix.platfom }}" "/p:Configuration="${{ matrix.configuration }}"
        
