name: Build C3 (Clang)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build C3 (Clang)
    strategy:
      matrix:
        platform: [x86, x64]
        configuration: [ClangDebug, ClangRwdi, ClangRelease]
    runs-on: windows-2022
    
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Dotnet restore
      run: msbuild Src/C3.sln "/t:restore"
      
    - name: Build MSVC
      run: msbuild Src/C3.sln "/p:Platform=${{ matrix.platform }}" "/p:Configuration="${{ matrix.configuration }}"
        
