name: Build C3 (MSVC)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build C3 (MSVC)
    strategy:
      matrix:
        platform: [x86, x64]
        configuration: [Debug, ReleaseWithDebInfo, Release]
    runs-on: windows-2022
    
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Dotnet restore
      run: msbuild Src/C3.sln "/t:restore"

    - name: Build MSVC
      run: msbuild Src/C3.sln /p:Platform=${{ matrix.platform }} /p:Configuration=${{ matrix.configuration }} "/t:GatewayConsoleExe;NodeRelayConsoleExe;NodeRelayDll;CebuLoader;ChannelLinter"
    
    - name: Build WebService
      run: dotnet publish -p:Platform=any -c ${{ matrix.configuration }} Src/WebController/Backend -o Bin/WebController 
        
